
[versions]
kotlin-version = "2.1.10"
ktor-version = "3.1.3"
logback-version = "1.4.14"
koin-version = "4.0.3"
mongo-version = "5.3.0"
google-api-client = "2.8.0"
dotenv = "6.4.1"

[libraries]
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor-version" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktor-version" }
ktor-bson-kotlinx= { module = "org.mongodb:bson-kotlinx", version.ref = "mongo-version" }
ktor-mongo-croutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongo-version" }
ktor-google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "google-api-client" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-server-status-page = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor-version" }
ktor-koin = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
ktor-koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }